parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: ./
  sourceType: module
env:
  es6: true
  node: true
extends:
  - plugin:prettier/recommended
plugins:
  - prettier
  - '@typescript-eslint'
rules:
  yoda: [error, always, { onlyEquality: true, exceptRange: true }]
  prettier/prettier: [error, {
    "singleQuote": true,
    "useTabs": true,
    "semi": false,
    "trailingComma": all,
  }]
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': [error, {functions: false, classes: false, variables: false}]
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-explicit-any': [warn, {fixToUnknown: true}]
